name: PR Word Card

on:
  schedule:
    - cron:  '10 06,08,10,12,14,16,18,20,21,22,00 * * *'


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - name: generate-word
      run: |
        getWord() {
          # Get a random word from the existing list
          NUM=$(echo $(( $RANDOM % 1000 + 3 )))
          n=1
          word=""
          while read line; do
            n=$((n+1))
            if [ $NUM == $n ]; then
             word=$(echo $line | awk '{print $2}')
             echo $word
            fi
          done < wordslist/first1000.yaml
        }

        validateWord() {
          echo "validating word: ${word}"
          files=`ls german/words`
          for eachfile in $files
          do
             if [[ $eachfile == *"${word}.md"  ]]; then
              echo "word ${word} already exist, trying a different one."
              return 1
             fi
          done
          echo "new word ${word} detected, calling goword"
          return 0
        }
        
        # Create the file with the proper file syntax
        word="$(getWord)"

        while ! validateWord; do
            word="$(getWord)"
        done

        pushd src/
          go build -o goword cmd/goword/main.go        
          filename="${word}.md"
          ./goword -w ${word}
          echo "WORD_ID=${word}" >> $GITHUB_ENV
          mv $word.md ../german/words/$filename
          rm goword
        popd
    - name: pull-request
      uses: peter-evans/create-pull-request@v3
      with:
          delete-branch: true
          title: Adding '${{ env.WORD_ID }}' word
          commit-message: '${{ env.WORD_ID }}'
          branch: '${{ env.WORD_ID }}'
          body: |
            Added a new German word
