name: PR Word Card

on:
  schedule:
    - cron:  '30 23 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - name: generate-word
      run: |
        # Get a random word from the existing list
        NUM=$(echo $(( $RANDOM % 100 + 3 )))
        n=1
        word=""
        while read line; do
          n=$((n+1))
          if [ $NUM == $n ]; then
           word=$(echo $line | awk '{print $2}')
          fi
        done < wordslist/first1000.yaml
        
        # Create the file with the proper file syntax
        
        echo "This is the word: ${word}"

        files=`ls german/words`
        nofiles=$(($(ls german/words| wc -l) + 1))
        for eachfile in $files
        do
           if [[ $eachfile == *"${word}.md"  ]]; then
            echo "Word already exist, trying a different one."
            exit 1
            // todo add a retry logic
           fi
        done

        pushd src/
          go build -o goword cmd/goword/main.go        
          filename="${nofiles}_${word}.md"
          ./goword -w ${word}
          mv $word.md ../german/words/$filename
          rm goword
        popd
    - name: pull-request
      uses: peter-evans/create-pull-request@v3