# on: [push]
on:
  workflow_dispatch:
    inputs:
      foobar:
        description: 'foobar'
        required: true
name: tweet!
jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Tweet
        env:
          WORD_ID: ${{ github.event.head_commit.message }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GOTWI_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          # GOTWI_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          # GOTWI_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          # GOTWI_API_KEY_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          # TWEET_CONTENT_PATH: ${{ secrets.TWEET_CONTENT_PATH }}
        run: |
          echo $COMMIT_MESSAGE
          pushd src/
            go build -o goword cmd/goword/main.go
            go build -o goword cmd/tweet/main.go
            ./goword -w ${WORD_ID} -c
            rm goword
            cat ${WORD_ID}.txt
          popd